### ISSUE TITLE
Specify format in README.md for IoT sensors

### ISSUE THREAD

**Issue by tanya-vedi** [tanya-vedi/SmartCityFramework#7]
It should include the sensor name, specification of the sensor, it's use and references.

**Comment by enkaypeter** [comment]
Should this be done in a tabular format ?

**Comment by tanya-vedi** [comment]
> Should this be done in a tabular format ?
Yes, preferably

**Comment by enkaypeter** [comment]
Alright..I'm on it.

**Comment by enkaypeter** [comment]
Done :+1:
